version: '3'

services: 
    app:
        build: ./
        container_name: nostradamus_app
        #command: sh -c "/wait && /root/app"
        depends_on: 
            - redis
        environment: 
            - WAIT_HOSTS=redis:6379
            - WAIT_HOSTS_TIMEOUT=300
            - WAIT_SLEEP_INTERVAL=30
            - WAIT_HOST_CONNECT_TIMEOUT=30

    redis:
        image: redis:alpine
        container_name: nostradamus_redis
        ports:
            - 6379:6379
        volumes: 
            - ./config/redis.conf:/redis.conf